### ISSUE TITLE
Slow printing

### ISSUE THREAD

**Issue by roguestereo** [brynthomas/pic32ssd1306#1]
Hi, I'm using your code as a base for a project I am doing. The printing is kinda slow, is there a way to make it print a string all at once instead of one by one?
Also, how did you create your font? Trying to make something larger.

**Comment by brynthomas** [comment]
This code was mostly written for clarity in terms of how it operates so speed wasn't a big priority. There are a lot of opportunities to make it faster, but there would probably be tradeoffs involved that would depend on your usage. I'm not planning on making any changes to this until I do something again that needs an SSD1306 screen.

I think I had probably written some separate script to convert from the original Tom Thumb font files. I had a look to see if I could still find that script, but unfortunately it's been so long that I couldn't find it.

**Comment by naazrael** [comment]
appreciate the reply regardless, i know this is a super old thread. It's been great learning from it, thank you!

**Comment by roguestereo** [comment]
appreciate the reply regardless, it's been very useful reading from your code, and learning from it. thanks for writing it and taking the time to look
